### ISSUE TITLE
missing double quotes to handle spaces in install path

### ISSUE THREAD

**Issue by phellmann** [ADN-DevTech/3dsMax-Python-HowTos#12]
I had an issue on windows with my 3dsMax install path.
It contains spaces and line 3 in the .sh files
`script=$(dirname $(readlink -f "$0"))`
is not working.
changing it with double quotes fixes the issue:
`script=$(dirname "$(readlink -f "$0")")`

**Comment by hugow** [comment]
Thanks for reporting this. I just opened a PR https://github.com/ADN-DevTech/3dsMax-Python-HowTos/pull/13 should be merged shortly.
