### ISSUE TITLE
pySide2 ui_loader sample error

### ISSUE THREAD

**Issue by phellmann** [ADN-DevTech/3dsMax-Python-HowTos#24]
calling win.show() is not showing the loaded ui.
I am trying to learn this stuff, so this is quite confusing, but I think it has to call `self.loaded_ui.show()` after line 24, no?

**Comment by hugow** [comment]
Just tried this and it seems to work. This sample is also provided in the installed version of 3dsMax in scripts/PythonSamples/Python3/PySide2/ui_loader.py. Does this one work for you (but I think they are the same)?

**Comment by phellmann** [comment]
Ah, I used my own ui file. And the big difference was, that its a QWindow and not a Widget, like yours.
So it makes sense, that .show() was not working.

**Comment by hugow** [comment]
Thanks for the feedback! I guess I can close this.
