### ISSUE TITLE
Struggling to install through gitbash.

### ISSUE THREAD

**Issue by jjobson98** [ADN-DevTech/3dsMax-Python-HowTos#39]
I've cloned the project, then moved the install.sh to the install directory (C:\Program Files\Autodesk\3ds Max 2023), then in the directory right click, run git bash as admin, and type ./install.sh. It starts to install it then I get this error:
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\

Anyone know how to fix this? I've tried recloning the repo and cloning straight into the install directory

**Comment by hugow** [comment]
Thanks for your message.
You should leave install.sh where it is (in the git clone).
Then you should cd to your max installation directory
Then you should:
/path/to/install/install.sh

(i.e. your working directory should be your max install directory, and from there you should invoke install with the proper path)
I hope this works.

**Comment by jjobson98** [comment]
Hi,

this fixed it thank you very much
